site_name: eln2.org
nav:
  - Home: index.md
  - Eln2 Agenda: agenda.md
  - Eln2 Progress: progress.md
  - Contributing: contributing.md
  - Library: library.md
  - Electrical Age Website: https://electrical-age.net
  - Electrical Age Wiki: https://wiki.electrical-age.net
theme: lumen
repo_url: https://github.com/eln2/eln2-web

markdown_extensions:
  - admonition
  - pymdownx.tasklist