site_name: eln2.org
nav:
  - Home: index.md
  - Eln2 Developer Plans: development.md
  - Eln2 Progress: progress.md
  - Library: library.md
  - Electrical Age Website: https://electrical-age.net
  - Electrical Age Wiki: https://wiki.electrical-age.net
theme: lumen
repo_url: https://github.com/eln2/eln2-web
